-- PLAYTOGETHER SHOP - SUPABASE SCHEMA
create extension if not exists pgcrypto;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  role text not null default 'customer' check (role in ('customer','admin')),
  balance bigint not null default 0 check (balance >= 0),
  created_at timestamptz not null default now()
);

create table if not exists services (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  description text,
  price bigint not null default 0 check (price >= 0),
  active boolean not null default true,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  service_id bigint references services(id) on delete set null,
  game_id text,
  character_name text,
  contact text,
  note text,
  quantity int not null default 1 check (quantity > 0),
  unit_price bigint not null default 0 check (unit_price >= 0),
  total bigint not null default 0 check (total >= 0),
  status text not null default 'pending'
    check (status in ('pending','processing','doing','completed','cancelled')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists deposits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null check (amount > 0),
  transfer_code text not null,
  proof_url text,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null,
  type text not null check (type in ('deposit','order','refund','adjustment')),
  reference_id bigint,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint references orders(id) on delete set null,
  rating int not null check (rating between 1 and 5),
  content text,
  visible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text,
  target_id bigint,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists orders_user_id_idx on orders(user_id);
create index if not exists orders_status_idx on orders(status);
create index if not exists deposits_user_id_idx on deposits(user_id);
create index if not exists deposits_status_idx on deposits(status);
create index if not exists transactions_user_id_idx on transactions(user_id);
create index if not exists notifications_user_id_idx on notifications(user_id);

alter table profiles enable row level security;
alter table services enable row level security;
alter table orders enable row level security;
alter table deposits enable row level security;
alter table transactions enable row level security;
alter table feedback enable row level security;
alter table notifications enable row level security;
alter table settings enable row level security;
alter table admin_logs enable row level security;

-- Helper function: checks current user's role without exposing passwords/secrets.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Public services/settings
create policy "services public read" on services for select using (active = true or public.is_admin());
create policy "services admin all" on services for all using (public.is_admin()) with check (public.is_admin());

create policy "settings public read" on settings for select using (true);
create policy "settings admin all" on settings for all using (public.is_admin()) with check (public.is_admin());

-- Profile
create policy "profile own read" on profiles for select using (auth.uid() = id or public.is_admin());
create policy "profile own update" on profiles for update using (auth.uid() = id or public.is_admin()) with check (auth.uid() = id or public.is_admin());

-- Orders
create policy "orders own read" on orders for select using (auth.uid() = user_id or public.is_admin());
create policy "orders own insert" on orders for insert with check (auth.uid() = user_id);
create policy "orders admin update" on orders for update using (public.is_admin()) with check (public.is_admin());

-- Deposits
create policy "deposits own read" on deposits for select using (auth.uid() = user_id or public.is_admin());
create policy "deposits own insert" on deposits for insert with check (auth.uid() = user_id);
create policy "deposits admin update" on deposits for update using (public.is_admin()) with check (public.is_admin());

-- Transactions
create policy "transactions own read" on transactions for select using (auth.uid() = user_id or public.is_admin());
create policy "transactions admin insert" on transactions for insert with check (public.is_admin());

-- Feedback
create policy "feedback visible read" on feedback for select using (visible = true or auth.uid() = user_id or public.is_admin());
create policy "feedback own insert" on feedback for insert with check (auth.uid() = user_id);
create policy "feedback admin update" on feedback for update using (public.is_admin()) with check (public.is_admin());

-- Notifications
create policy "notifications own read" on notifications for select using (auth.uid() = user_id or public.is_admin());
create policy "notifications own update" on notifications for update using (auth.uid() = user_id or public.is_admin()) with check (auth.uid() = user_id or public.is_admin());
create policy "notifications admin insert" on notifications for insert with check (public.is_admin());

-- Logs
create policy "logs admin read" on admin_logs for select using (public.is_admin());
create policy "logs admin insert" on admin_logs for insert with check (public.is_admin());

-- Trigger profile creation after signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, username, display_name)
  values (
    new.id,
    split_part(coalesce(new.email, new.id::text), '@', 1),
    split_part(coalesce(new.email, new.id::text), '@', 1)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Seed services
insert into services(name,slug,description,price) values
('Cày tiền sao','cay-tien-sao','Cày tiền sao Play Together',10000),
('Dắt thẻ','dat-the','Hỗ trợ dắt thẻ',10000),
('Làm cần quái vật','lam-can-quai-vat','Nhận làm cần quái vật',10000),
('Kim Cương Xanh','kim-cuong-xanh','Nhận kiếm Kim Cương Xanh',10000),
('Kim Cương Đỏ','kim-cuong-do','Nhận kiếm Kim Cương Đỏ',10000),
('Câu bóng 6','cau-bong-6','Nhận câu bóng 6',10000),
('Câu bóng 7','cau-bong-7','Nhận câu bóng 7',10000),
('Cho thuê map trống','cho-thue-map-trong','Cho thuê map trống',10000)
on conflict(slug) do nothing;

insert into settings(key,value) values
('shop_name','PTShop'),
('zalo','0849414809'),
('facebook','#'),
('discord','#'),
('bank_name','YOUR_BANK'),
('bank_account','YOUR_ACCOUNT'),
('bank_owner','YOUR_NAME'),
('transfer_template','NAPTIEN {username}')
on conflict(key) do nothing;

-- IMPORTANT:
-- Never place SUPABASE_SERVICE_ROLE_KEY in browser code.
-- For approving deposits and changing balances, use trusted server-side code/RPC.
-- The starter UI intentionally does not fake automatic bank verification.
